# Generated by Django 5.2.6 on 2026-03-09 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='class_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='subject',
            name='section',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
