# Generated by Django 5.2.6 on 2026-03-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_subject_class_name_subject_section'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='student',
            name='branch',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='subject',
            name='branch',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='timetable',
            name='branch',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='timetable',
            name='semester',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('day', 'hour', 'branch', 'section', 'semester')},
        ),
    ]
